services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: differ
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
