ktor:
    application:
        modules:
            - com.joebrothers.differ.server.ApplicationKt.module
    deployment:
        port: 8080
database:
  url: "r2dbc:postgresql://localhost:5432/differ"
  user: username
  password: password
