[versions]
argon2-jvm = "2.12"
detekt = "2.0.0-alpha.1"  # TODO: https://github.com/detekt/detekt/issues/8745
exposed = "1.0.0-rc-4"
h2 = "2.3.232"
konvert = "4.4.0"
koin-bom = "4.1.1"
kotlin = "2.3.0"
ksp = "2.3.4"
ktor = "3.3.3"
ktlint-plugin = "14.0.1"
logback = "1.4.14"
postgres = "42.7.8"
r2dbc-postgresql = "1.1.1.RELEASE"

[libraries]
# ktor
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-rate-limit = { module = "io.ktor:ktor-server-rate-limit", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }

# db
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
r2dbc-postgresql = { module = "org.postgresql:r2dbc-postgresql", version.ref = "r2dbc-postgresql" }

# koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-ktor = { module = "io.insert-koin:koin-ktor" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j" }

# other
argon2-jvm = { module = "de.mkammerer:argon2-jvm", version.ref = "argon2-jvm" }
konvert = { module = "io.mcarle:konvert", version.ref = "konvert" }
konvert-api = { module = "io.mcarle:konvert-api", version.ref = "konvert" }
konvert-koin-annotations = { module = "io.mcarle:konvert-koin-annotations", version.ref = "konvert" }
konvert-koin-injector = { module = "io.mcarle:konvert-koin-injector", version.ref = "konvert" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# test
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint-plugin = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
